const { PUBLIC_SCHEMA_ID, PUBLIC_API_KEY, PUBLIC_TEMPLATE_ID, PUBLIC_BASE_URL, PUBLIC_REGULA_ENDPOINT }: any = globalThis

export const envConfig = {
  PUBLIC_SCHEMA_ID: PUBLIC_SCHEMA_ID || import.meta.env.PUBLIC_SCHEMA_ID,
  PUBLIC_API_KEY: PUBLIC_API_KEY || import.meta.env.PUBLIC_API_KEY,
  PUBLIC_TEMPLATE_ID: PUBLIC_TEMPLATE_ID || import.meta.env.PUBLIC_TEMPLATE_ID,
  PUBLIC_BASE_URL: PUBLIC_BASE_URL || import.meta.env.PUBLIC_BASE_URL,
  PUBLIC_REGULA_ENDPOINT: PUBLIC_REGULA_ENDPOINT || import.meta.env.PUBLIC_REGULA_ENDPOINT
};